### ISSUE TITLE
some bug in there.

### ISSUE THREAD

**Issue by axiaoxin** [mengzhuo/yaml-to-go#1]
type the yaml context by manual like this:

```
out:
  in:
    - 1
    - 2
````
convert to

```
type AutoGenerated struct {
	Out string `yaml:"out"`
}
```

copy from other it is work right

**Comment by jojomi** [comment]
yes, it is broken.

**Comment by leefernandes** [comment]
it seems to be very picky about indentation, requiring 4 spaces

**Comment by Zhwt** [comment]
Seems related to line break types.
When edit, copy & paste from notepad++ using LF as line break everything was fine, but if I edit and hit return in the web editor it will generate wrong structs.
